server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: customerDemo1
  datasource:
    url: jdbc:mysql://localhost:3306/cloudtest
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19950912

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
